### ISSUE TITLE
你好 为什么使用u-table,  el-table里面的属性 cell-style ，cell-class-name动态修改单元格样式都没有作用了？

### ISSUE THREAD

**Issue by bb5201314** [u-leo/umy-ui#100]
你好 为什么使用u-table,  el-table里面的属性 cell-style ，cell-class-name动态修改单元格样式都没有作用了？

**Comment by livelyPeng** [comment]
给出复现链接，或者写demo发群里，

**Comment by bb5201314** [comment]
你好，不好意思，那个是我用错了方法一个是返回对象一个是返回样式，另外还有个问题想请教下，这个u-table
的height 支持获取屏幕高度 动态改变不？比如刚开始加载是600，我桌面缩放了，计算出800，重新赋值

**Comment by livelyPeng** [comment]
http://www.umyui.com/umycomponent/tableWithPagination




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月7日(星期二) 下午2:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] 你好 为什么使用u-table,  el-table里面的属性 cell-style ，cell-class-name动态修改单元格样式都没有作用了？ (#100)





 
你好，不好意思，那个是我用错了方法一个是返回对象一个是返回样式，另外还有个问题想请教下，这个u-table
 的height 支持获取屏幕高度 动态改变不？比如刚开始加载是600，我桌面缩放了，计算出800，重新赋值
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bb5201314** [comment]
ipcRenderer.on('sizeEvent',(data,size) => {
           console.log(size)
           this.height =size.height
        })
我在桌面变化的时候去设置这个height跟我不设置height高度是一样的效果，他把表头都带着滚动了，并且横向滚动条一直到最底部了
