### ISSUE TITLE
贵ui重置了elementui的初始化

### ISSUE THREAD

**Issue by wzch333** [u-leo/umy-ui#48]
同时引入umy-ui;element-ui;element ui我是cdn引入的 umy-ui打包引入
在配置按钮默认大小的时候;初始化了我的配置 
Vue.use(Element, {
  size: 'small',
});
页面不生效

**Comment by livelyPeng** [comment]
没懂意思 写个demo

**Comment by wzch333** [comment]
> 没懂意思 写个demo

我在mainjs里初始化element size大小
Vue.use(Element, {
size: 'small',
});
不生效

**Comment by livelyPeng** [comment]
你没生效 跟umy啥关系，喊你写个demo&nbsp; 不生效&nbsp; 你不知道啥叫demo吗？&nbsp;https://codepen.io/



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月14日(星期三) 上午9:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] 贵ui重置了elementui的初始化 (#48)





  
没懂意思 写个demo
  
我在mainjs里初始化element size大小
 Vue.use(Element, {
 size: 'small',
 });
 不生效

**Comment by wzch333** [comment]
> 你没生效 跟umy啥关系，喊你写个demo&nbsp; 不生效&nbsp; 你不知道啥叫demo吗？&nbsp;https://codepen.io/
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月14日(星期三) 上午9:04 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [u-leo/umy-ui] 贵ui重置了elementui的初始化 (#48) 没懂意思 写个demo 我在mainjs里初始化element size大小 Vue.use(Element, { size: 'small', }); 不生效 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.



> 你没生效 跟umy啥关系，喊你写个demo&nbsp; 不生效&nbsp; 你不知道啥叫demo吗？&nbsp;https://codepen.io/
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月14日(星期三) 上午9:04 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [u-leo/umy-ui] 贵ui重置了elementui的初始化 (#48) 没懂意思 写个demo 我在mainjs里初始化element size大小 Vue.use(Element, { size: 'small', }); 不生效 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

打包生成没办法贴代码 我自认为已经描述的很清楚了
算了 我自己改改你的源码吧

**Comment by livelyPeng** [comment]
没办法贴代码？你把你代码写个demo。用给你的链接写，写cdn啊&nbsp; 有啥问题嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月14日(星期三) 中午11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] 贵ui重置了elementui的初始化 (#48)





  
你没生效 跟umy啥关系，喊你写个demo&nbsp; 不生效&nbsp; 你不知道啥叫demo吗？&nbsp;https://codepen.io/
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年4月14日(星期三) 上午9:04 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [u-leo/umy-ui] 贵ui重置了elementui的初始化 (#48) 没懂意思 写个demo 我在mainjs里初始化element size大小 Vue.use(Element, { size: 'small', }); 不生效 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
   
你没生效 跟umy啥关系，喊你写个demo&nbsp; 不生效&nbsp; 你不知道啥叫demo吗？&nbsp;https://codepen.io/
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年4月14日(星期三) 上午9:04 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [u-leo/umy-ui] 贵ui重置了elementui的初始化 (#48) 没懂意思 写个demo 我在mainjs里初始化element size大小 Vue.use(Element, { size: 'small', }); 不生效 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
打包生成没办法贴代码 我自认为已经描述的很清楚了
 算了 我自己改改你的源码吧
