### ISSUE TITLE
ux-grid列是动态变化的，通过reloadColumn配置列，但包含有操作列里面有按钮，通过什么属性配置呢？在模板中用插槽无效

### ISSUE THREAD

**Issue by md-wsm** [u-leo/umy-ui#92]

**Comment by livelyPeng** [comment]
自己自定义单元格啊，为啥要reloadColumn?  把列用数组 v-for啊

**Comment by md-wsm** [comment]
开始是在ux-table-column上使用v-for="(item, index) in column"，但有部分列是异步获取的，获取后更新column发现视图未更新，此时才想起使用reloadColumn(column)，此方法会使模板中的内容被替换掉，但用不知怎么才能渲染按钮等非常规文本

**Comment by livelyPeng** [comment]
refreshColumn
刷新列配置（对于动态修改属性、显示/隐藏列等场景下可能会用到）
—






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月18日(星期三) 中午11:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] ux-grid列是动态变化的，通过reloadColumn配置列，但包含有操作列里面有按钮，通过什么属性配置呢？在模板中用插槽无效 (#92)





 
开始是在ux-table-column上使用v-for="(item, index) in column"，但有部分列是异步获取的，获取后更新column发现视图未更新，此时才想起使用reloadColumn(column)，此方法会使模板中的内容被替换掉，但用不知怎么才能渲染按钮等非常规文本
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by md-wsm** [comment]
改用v-for了，可以了，之前不知怎么回事 谢谢
