### ISSUE TITLE
ux-grid 横向滚动卡顿

### ISSUE THREAD

**Issue by suqinghzhou2019** [u-leo/umy-ui#93]
共53列，3000多行，页面实际渲染了18列，纵向滚动没问题，横向滚动有些卡顿，请问是数据量的问题吗

**Comment by livelyPeng** [comment]
编辑表格 请看文档

**Comment by suqinghzhou2019** [comment]
> 编辑表格 请看文档

确实是使用了编辑表格，开启了keep-source，但是没发现与官网示例有太大区别，麻烦直接说下

**Comment by livelyPeng** [comment]
没空 自己去发现你的不同。文档不卡 你卡，你就自己找问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月19日(星期四) 上午8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] ux-grid 横向滚动卡顿 (#93)





  
编辑表格 请看文档
  
确实是使用了编辑表格，开启了keep-source，但是没发现与官网示例有太大区别，麻烦直接说下
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by suqinghzhou2019** [comment]
> 没空 自己去发现你的不同。文档不卡 你卡，你就自己找问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年8月19日(星期四) 上午8:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [u-leo/umy-ui] ux-grid 横向滚动卡顿 (#93) 编辑表格 请看文档 确实是使用了编辑表格，开启了keep-source，但是没发现与官网示例有太大区别，麻烦直接说下 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
额，我调整列宽，实际渲染8列，就不会卡顿了，希望您可以亲自试下页面渲染更多的列会不会卡顿
