### ISSUE TITLE
babel-helper-vue-jsx-merge-props应该在运行依赖

### ISSUE THREAD

**Issue by daydaystar** [u-leo/umy-ui#96]
安装umy-ui包
运行提示babel-helper-vue-jsx-merge-props找不到

**Comment by livelyPeng** [comment]
大哥 那你去百度下 这个包干嘛的呀，自己去安装啊

**Comment by daydaystar** [comment]
你组件的依赖……你写在开发依赖里

**Comment by daydaystar** [comment]
用你的组件还得单独去下别的包 你觉得合理吗……

**Comment by livelyPeng** [comment]
no,这是你项目自己没有配置需要的插件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月24日(星期二) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] babel-helper-vue-jsx-merge-props应该在运行依赖 (#96)





 
你组件的依赖……你写在开发依赖里
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daydaystar** [comment]
你看element-ui 这个包都是放运行依赖

**Comment by livelyPeng** [comment]
自己去找问题，自己吧依赖删除 重新安装！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月24日(星期二) 下午4:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] babel-helper-vue-jsx-merge-props应该在运行依赖 (#96)





 
你看element-ui 这个包都是放运行依赖
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daydaystar** [comment]
之前没人说 他们都是先下了element-ui 然后才用你这个

**Comment by daydaystar** [comment]
你不改算了 我又无所谓

**Comment by livelyPeng** [comment]
no，  我只能告诉你你的项目搭建有问题，一般来说必然有
![image](https://user-images.githubusercontent.com/32978177/130584911-b6970371-5f0c-49fb-8d90-7851f08af973.png)
这个配置，
![image](https://user-images.githubusercontent.com/32978177/130584944-2ec50058-d34d-46be-bdd4-27293d16bb7f.png)

**Comment by livelyPeng** [comment]
如果没有 自己去配置 自己去下载 安装！

**Comment by daydaystar** [comment]
我用的是vue-cli3搭建的，你的组件使用要求这么高吗……

**Comment by daydaystar** [comment]
而且babel这些……不是你开发组件时的开发依赖吗……  发布后 还要求使用者也有相同的环境吗……

**Comment by livelyPeng** [comment]
打住，你的问题只需要自己 npm i
![Uploading image.png…]()

**Comment by livelyPeng** [comment]
打住，你的问题只需要自己 npm i 
babel-helper-vue-jsx-merge-props

**Comment by daydaystar** [comment]
行 不说了 我还是保持我的观点

**Comment by livelyPeng** [comment]
![image](https://user-images.githubusercontent.com/32978177/130588111-6d6fd211-60eb-473e-bc61-4e112568e902.png)
🤭

**Comment by daydaystar** [comment]
明明就是你自己依赖了 不写进去 还得让用户自己安装！

**Comment by livelyPeng** [comment]
打住，你说得有道理，但是你使用东西，让你安装的模块 怎么了？你安装下又不会少块肉




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月24日(星期二) 下午4:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] babel-helper-vue-jsx-merge-props应该在运行依赖 (#96)





 
明明就是你自己依赖了 不写进去 还得让用户自己安装！
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 4ever88** [comment]
人家开发这个控件给你，没收你钱就已经很不错了。还在那里叽叽歪歪。你这么厉害你自己开发一个去！吵死了。

**Comment by daydaystar** [comment]
> 家庭开发这个控件给你，没收你钱就已经很不错了。
> […](#)
> On Aug 24, 2021, at 17:00, 谷地南瓜 ***@***.***> wrote: ﻿ Closed #96. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我提合理意见，就算作者不接受，也轮不到你在这狗叫吧！你说的对，你确实挺吵的！

**Comment by livelyPeng** [comment]
@daydaystar 好了 大哥 都是前端 都是打工人 不容易，别吵了。

**Comment by livelyPeng** [comment]
@4ever88 哈哈哈   别吵架  哈哈
