### ISSUE TITLE
ux-grid表格嵌套el-select时选项位置出现偏移

### ISSUE THREAD

**Issue by wangsiyu1995** [u-leo/umy-ui#99]
当ux-grid表格高度固定时，嵌套el-select选项位置出现偏移，并且不能使用el-select的popper-append-to-body属性（如果使用还会出现新的问题）

**Comment by livelyPeng** [comment]
截图看看呢，

**Comment by wangsiyu1995** [comment]
![3e3aba5e048f9ef210b363277de5be9](https://user-images.githubusercontent.com/72593505/132444633-d73b1670-5fd9-450c-a10d-a2393c57aa04.png)
当增加行超过表格固定高度之后，弹出下拉框被覆盖了，下拉框选项没有自动弹到上面

**Comment by wangsiyu1995** [comment]
而且当点击下拉框时表格滚动条为什么会自动向上伸缩一点呢？为什么还会出现横向滚动条呢？（表格原来没有横向滚动条）

**Comment by livelyPeng** [comment]
不解决这样的问题，请自行想办法！不是啥大问题，还有就是请一定要理解&nbsp; 一个道理没有十全十美的东西！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 中午12:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [u-leo/umy-ui] ux-grid表格嵌套el-select时选项位置出现偏移 (#99)





 

 当增加行超过表格固定高度之后，弹出下拉框被覆盖了，下拉框选项没有自动弹到上面
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
